providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install"]
env = { NODE_ENV = "development" }

[phases.build]
cmds = ["yarn build"]
env = { NODE_ENV = "production" }
