providers = ["node"]
buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1741046653"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]
env = { NODE_ENV = "production" }
