providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install --no-fund --no-audit --production=false"]
env = { NODE_ENV = "development" }

[phases.build]
cmds = ["npm run build"]
env = { NODE_ENV = "production" }
